//
// Created by fox on 16.08.23.
//

#ifndef DEEPCLIENT_PHP_EXTENSION_CPP_DEEPCLIENT_H
#define DEEPCLIENT_PHP_EXTENSION_CPP_DEEPCLIENT_H


class DeepClient {

};


#endif //DEEPCLIENT_PHP_EXTENSION_CPP_DEEPCLIENT_H
